### ISSUE TITLE
How can I add this step to my Bitrise workflow ?

### ISSUE THREAD

**Issue by OhMyApp** [SimonRice/bitrise-step-sentry-dsym-upload#1]
Hello,
Is it posible to add this step inside a Bitrise workflow ?

**Comment by SimonRice** [comment]
Hi there,

I keep meaning to actually release this build step, which will make this much easier.  Real artists ship & all that.

For the time being though:

1.  On your project's settings, go to the `bitrise.yml` tab.

<img width="1004" alt="Screenshot 2020-03-25 at 8 55 31 am" src="https://user-images.githubusercontent.com/548577/77518892-723cb980-6e76-11ea-96ae-c55e641904f2.png">

2.  At the right point on your YAML file (after `xcode-archive` is a good place), add something like this:

```
    - git::https://github.com/SimonRice/bitrise-step-sentry-dsym-upload.git@main:
        inputs:
        - sentry_project_slug: YOUR_PROJECT_SLUG
        - sentry_org_slug: YOUR_ORG_SLUG
```

3.  Save & the build step will then be configurable via Bitrise's UI.

Finally if you find any issue with the work so far, feel free to point this to your own fork (& raise a PR, etc.).

I hope this helps.
